### PR TITLE
Additional Account Ref Date field

### PR DESCRIPTION
**Pull request by stevewilliamsuk**
Please accept my pull request to add an additional option for the Accounting Reference Date field to get out the dd/mm date as a single string.

Also moves out types to matching files.

### CODE REVIEW

**Comment by kevbite** [comment]
Nice to see you guys extending our CompaniesHouse.NET package, once you're happy with the changes it would be nice to see it go back in to the originating source (https://github.com/LiberisLabs/CompaniesHouse.NET) then other people will be able to benefit via the public NuGet package.

**Comment by stevewilliamsuk** [comment]
Yes Kevin we will eventually get round to this we had taken the assumption that you would want Unit Tests to be added before the code could be merged back into your repository.

**Comment by kevbite** [comment]
That would be great! Looking forward to the pull request!

**Comment by stevewilliamsuk** [comment]
Pull request #3 replaces this one

**Pull request closed without merging**
